---
# Step 10
- name: Start OpenVPN service
  hosts: vpn_server
  vars_files:
    - vars/main-vars.yml
  vars:
    - ansible_port: "{{ ssh_port }}"
  tasks:
    - name: Start OpenVPN service
      become: yes
      service:
        name: openvpn-server@server.service
        enabled: yes
        state: started
        daemon_reload: yes
