---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      package:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Ensure build dependencies are installed (RedHat)
      package:
        name:
          - openssh-server
          - openssh-clients
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure build dependencies are installed (Fedora)
      package:
        name: procps
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Ensure build dependencies are installed (Debian)
      package:
        name:
          - openssh-server
          - openssh-client
          - acl
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure auth.log file is present
      copy:
        dest: /var/log/auth.log
        content: ""
        force: false
        mode: 0644
      when: ansible_distribution == 'Debian'

- name: Init
  import_playbook: ../../init.yml
  vars:
    extra_vars:
      # OpenVPN in Docker will not have example server config. A workaround is to copy it from localhost
      openvpn_remote_example_config: no
      # need user_home set explicitly for commands that use ~ and become=yes
      user_home: /root

# server
- name: VPN post provision
  import_playbook: ../../vpn-post-provision.yml
  vars:
    extra_vars:
      # OpenVPN in Docker will not have example client config. A workaround is to copy it from localhost
      openvpn_remote_example_config: no
      user_home: /root

# client
- name: Add client
  import_playbook: ../../add-client.yml

- name: Remove client
  import_playbook: ../../remove-client.yml
