---
- name: Update apt cache (on Debian)
  become: yes
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Ensure SSH daemon is running and enabled.
  service:
    name: ssh
    state: started
    enabled: true
  when: ansible_os_family == 'Debian'
